fix(dedup rebuild): if possible, use same backend during rebuild
threefoldtech/0-stor_v2 pull request #142
Opened 2024-12-11 11:01 UTC by iwanbk

Fixes #5 

TODO:
- fix error level
- looks for possibility of merging save_data and save_rebuild_data
  if not possible, reduce code duplication

2024-12-13 09:13 UTC, LeeSmet requested changes

2024-12-13 09:13 UTC, LeeSmet commented on zstor/src/actors/zstor.rs
> +                            warn!("Shard {} is DIFFERENT", i);
This shouldn't be a warning, not sure if these logs here are needed at all

2024-12-13 09:32 UTC, iwanbk commented on zstor/src/actors/zstor.rs
> +                            warn!("Shard {} is DIFFERENT", i);
> not sure if these logs here are needed at all

You're correct for the other two logs:
```rust
debug!("Shard {} is the SAME", i);
debug!("Shard {} is MISSING", i);
```
I can remove it.

But i think the different case is needed and should be a `warn`, because it is unexpected to happens

2024-12-17 10:15 UTC, LeeSmet approved these changes

2024-12-17 10:16 UTC, merged