Feat/explorer client
threefoldtech/0-stor_v2 pull request #45
Opened 2021-05-20 17:14 UTC by xmonader

2021-05-21 13:14 UTC, DylanVerstraete commented
@OmarElawady good changes! Well done :ship:

2021-05-25 11:09 UTC, LeeSmet requested changes
In addition to the comments, please

- rebase on master
- format files (`rustfmt` / `cargo fmt`)
- run `clippy` and address the mentioned warnings in the `grid_explorer_client` dir (there are some warnings on the current master sadly)

2021-05-25 11:09 UTC, LeeSmet commented on grid_explorer_client/src/workload.rs
> +    }
Replace this with an `impl Display for ZdbMode`

2021-05-25 11:09 UTC, LeeSmet commented on grid_explorer_client/src/workload.rs
> +    }
Replace this with an `impl Display for ZdbMode`

2021-05-26 18:11 UTC, OmarElawady commented on grid_explorer_client/src/lib.rs
> +        while x.as_secs() < timeout {
yes, modified and tested against both bad scenarios.

2021-05-26 18:16 UTC, OmarElawady commented on grid_explorer_client/src/lib.rs
> +    pub async fn workload_decommission(&self, wid: i64) -> Result<bool, ExplorerError> {
I don't think there's a distinction between them. The distinction is beween (<= 3) which indicates the workload is deployed or in the process of being deployed, and (> 3) which indicates delete/to be deleted. This is because the explorer returns 400 error when the workload is deleted/to be deleted.

2021-05-26 22:48 UTC, OmarElawady commented
Still woking on zdb password encryption

2021-05-27 18:27 UTC, OmarElawady commented
@LeeSmet 
Pushed the zdb password encryption part (verified by matching it with the js-sdk one with the same nonce)

2021-05-30 00:30 UTC, LeeSmet approved these changes

2021-05-30 10:29 UTC, merged